staging and produciton restriction

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -1,5 +1,17 @@
 name: Deploy
 on:
+  workflow_dispatch:
+    inputs:
+      aws-env:
+        description: "AWS Elastic Beanstalk Environment"
+        required: true
+        default: "development"
+        type: string
+      github-env:
+        description: "Github Environment"
+        required: true
+        default: "staging"
+        type: string
   workflow_call:
     inputs:
       aws-env:
@@ -24,6 +36,11 @@ jobs:
       name: ${{ inputs.github-env }}
       url: "http://${{ steps.get-cname.outputs.aws_env_cname }}"
     steps:
+      - name: Avoid deploying to production using a non production env
+        if: inputs.aws-env == 'my-app-prod' && inputs.github-env != 'production'
+        run: |
+          echo "::error::Cannot deploy to production using a non prodcuction environment"
+          exit 1
       - name: Checkout
         uses: actions/checkout@v3
         with:
